### ISSUE TITLE
"package:url2pdf/apikey.dart" problem

### ISSUE THREAD

**Issue by HassanDev13** [colt005/UrltoPdf#1]
i went to try it but show me this problem
<img width="414" alt="Capture" src="https://user-images.githubusercontent.com/48941486/72450779-d5dda300-37b2-11ea-9180-562ff2966a4e.PNG">

**Comment by colt005** [comment]
Create a new dart file called apikey.dart and keep the html2pdf API key in that file. I will be updating the READMe by tonight so that it would be clearer.

**Comment by colt005** [comment]
@HassanDev13 I have updated the README file. Please have a look at it for detailed instructions.
[README](https://github.com/colt005/UrltoPdf/blob/master/README.md)
